(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(*Non-dimensional Momentum Range*)
n=100.;
ymax=20.;
ymin=0.01;
hy=(ymax-ymin)/(n-1.);
y1=Table[i,{i,ymin,ymax,hy}];
(*Initial Non-dimensional Temperature and Time*)
zin=1.00003;
m=1000.;
xin=me/10.;xfin=30.;
hx=(xfin-xin)/(m-1.);


(* ::Input::Initialization:: *)
(*All Parameters in MeV*)
me=0.511;
Mpl=1.22091 10^19 10^3;
GF=1.1663787 10^-5 10^-6;
gL=0.727;
gR=0.233;
g\[Mu]L=-0.273;
(*Fine-structure Constant*)
\[Alpha]=1/137.035999;


(* ::Input::Initialization:: *)
(*Interpolation Order*)
interpOrder=10;


(* ::Input::Initialization:: *)
(*Solver Parameters*)
AG=6;
MP=1000;


(* ::Input::Initialization:: *)
D1[q1_,q2_,q3_,q4_]:=Which[
(q1+q2>q3+q4)&&(q1+q4>q3+q2)&&(q4+q3+q2>=q1)&&(q1>q2)&&(q3>q4)&&(ymin<q2<ymax),1/2. (q2+q3+q4-q1),
(q1+q2>q3+q4)&&(q1+q4<q3+q2)&&(q1>q2)&&(q3>q4)&&(ymin<q2<ymax),q4,
(q1+q2<q3+q4)&&(q1+q4<q3+q2)&&(q4+q2+q1>=q3)&&(q1>q2)&&(q3>q4)&&(ymin<q2<ymax),1/2. (q1+q2+q4-q3) ,
(q1+q2<q3+q4)&&(q1+q4>q3+q2)&&(q1>q2)&&(q3>q4)&&(ymin<q2<ymax),q2,True,0.]; 

D2[q1_,q2_,q3_,q4_]:=Which[
(q1+q2>q3+q4)&&(q1+q4>q3+q2)&&(q4+q3+q2>=q1)&&(q1>q2)&&(q3>q4)&&(ymin<q1<ymax)&&(ymin<q2<ymax)&&(ymin<q3<ymax)&&(ymin<q4<ymax),1/12. ((q1-q2)^3+2.(q3^3+q4^3)-3.(q1-q2)(q3^2+q4^2)),
(q1+q2>q3+q4)&&(q1+q4<q3+q2)&&(q1>q2)&&(q3>q4)&&(ymin<q1<ymax)&&(ymin<q2<ymax)&&(ymin<q3<ymax)&&(ymin<q4<ymax),1/3. q4^3,
(q1+q2<q3+q4)&&(q1+q4<q3+q2)&&(q4+q2+q1>=q3)&&(q1>q2)&&(q3>q4)&&(ymin<q1<ymax)&&(ymin<q2<ymax)&&(ymin<q3<ymax)&&(ymin<q4<ymax),1/12. (-(q1+q2)^3-2.q3^3+2.q4^3+3.(q1+q2)(q3^2+q4^2)),
(q1+q2<q3+q4)&&(q1+q4>q3+q2)&&(q1>q2)&&(q3>q4)&&(ymin<q1<ymax)&&(ymin<q2<ymax)&&(ymin<q3<ymax)&&(ymin<q4<ymax),1/6. q2(3.q3^2+3.q4^2-3.q1^2-q2^2),True,0.];

D3[q1_,q2_,q3_,q4_]:=Which[
(q1+q2>q3+q4)&&(q1+q4>q3+q2)&&(q4+q3+q2>=q1)&&(q1>q2)&&(q3>q4)&&(ymin<q2<ymax),1/60. (q1^5-5.q1^3 q2^2+5.q1^2 q2^3-q2^5-5.q1^3 q3^2+5.q2^3 q3^2+5.q1^2 q3^3+5.q2^2 q3^3-q3^5-5.q1^3 q4^2+5.q2^3 q4^2+5.q3^3 q4^2+5.q1^2 q4^3+5.q2^2 q4^3+5.q3^2 q4^3-q4^5),
(q1+q2>q3+q4)&&(q1+q4<q3+q2)&&(q1>q2)&&(q3>q4)&&(ymin<q2<ymax),1/30. q4^3 (5.q1^2+5.q2^2+5.q3^2-q4^2),
(q1+q2<q3+q4)&&(q1+q4<q3+q2)&&(q4+q2+q1>=q3)&&(q1>q2)&&(q3>q4)&&(ymin<q2<ymax),1/60. (q3^5-5.q3^3 q4^2+5.q3^2 q4^3-q4^5-5.q3^3 q1^2+5.q4^3 q1^2+5.q3^2 q1^3+5.q4^2 q1^3-q1^5-5.q3^3 q2^2+5.q4^3 q2^2+5.q1^3 q2^2+5.q3^2 q2^3+5.q4^2 q2^3+5.q1^2 q2^3-q2^5),
(q1+q2<q3+q4)&&(q1+q4>q3+q2)&&(q1>q2)&&(q3>q4)&&(ymin<q2<ymax),1/30. q2^3 (5.q1^2+5.q3^2+5.q4^2-q2^2),True,0.];


(* ::Input::Initialization:: *)
(*Modified UnitStep to Avoid Singularities*)
unitstep[\[Lambda]_]:=unitstep[\[Lambda]]=1.-UnitStep[-\[Lambda]];


(* ::Input::Initialization:: *)
(*Electromagnetic Distribution: e^\[PlusMinus]*)
fe[\[Beta]_,\[Gamma]_]:=fe[\[Beta],\[Gamma]]=1/(1.+Exp[\[Beta]/\[Gamma]]);


(* ::Input::Initialization:: *)
(*\[Nu]e and \[Nu]\[Mu] Distributions*)
f\[Nu]0[\[Alpha]_]:=f\[Nu]0[\[Alpha]]=1/(1.+Exp[\[Alpha]/1.00003]);


(* ::Input::Initialization:: *)
(*Electron Mass Correction*)
\[Delta]me2[z_Real,x_Real]:=\[Delta]me2[z,x]=(2\[Pi] \[Alpha] z^2)/3.+(4\[Alpha])/\[Pi] NIntegrate[k^2/Ek[k,x] 1/(Exp[Ek[k,x]/z]+1.),{k,ymin,ymax}];
\[Delta]m\[Gamma]2[z_Real,x_Real]:=\[Delta]m\[Gamma]2[z,x]=(8\[Alpha])/\[Pi] NIntegrate[k^2/Ek[k,x] 1/(Exp[Ek[k,x]/z]+1.),{k,ymin,ymax}];


(* ::Input::Initialization:: *)
(*Energy Density Correction*)
\[Rho]intBar[z_Real,x_Real]:=-(1/(2\[Pi]^2))NIntegrate[k^2/Ek[k,x] \[Delta]me2[z,x]/(Exp[Ek[k,x]/z]+1.)+k/2. \[Delta]m\[Gamma]2[z,x]/(Exp[k/z]-1.),{k,ymin,ymax}]+z/(2.\[Pi]^2) NIntegrate[(4\[Pi] \[Alpha])/3 k^2/Ek[k,x] z/(Exp[Ek[k,x]/z]+1.)+(4\[Alpha])/(\[Pi] z^2) k^2/Ek[k,x] 1/(Exp[Ek[k,x]/z]+1.) NIntegrate[\[Lambda]^2 Exp[Ek[\[Lambda],x]/z]/(Exp[Ek[\[Lambda],x]/z]+1.)^2,{\[Lambda],ymin,ymin}]+(4\[Alpha])/(\[Pi] z^2) k^2 Exp[Ek[k,x]/z]/(Exp[Ek[k,x]/z]+1)^2 NIntegrate[\[Lambda]^2/Ek[\[Lambda],x] 1/(Exp[Ek[\[Lambda],x]/z]+1.),{\[Lambda],ymin,ymax}]+(8\[Alpha])/(\[Pi] z^2) k/2 1/(Exp[k/z]-1.) NIntegrate[\[Lambda]^2 Exp[\[Lambda]/z]/(Exp[\[Lambda]/z]+1.)^2,{\[Lambda],ymin,ymax}]+(8\[Alpha])/(\[Pi] z^2) k/2 (k Exp[k/z])/(Exp[k/z]-1.)^2 NIntegrate[\[Lambda]^2/Ek[\[Lambda],x] 1/(Exp[Ek[\[Lambda],x]/z]+1.),{\[Lambda],ymin,ymax}],{k,ymin,ymax}];


(* ::Input::Initialization:: *)
(*Non-dimensional Hubble Parameter*)
H[f\[Nu]e_,f\[Nu]\[Mu]_,z_Real,x_Real]:=H[f\[Nu]e,f\[Nu]\[Mu],z,x]=(me/x)^2 Sqrt[(8 N[\[Pi]])/(3.((Mpl)^2) ) (\[Rho]Bar[f\[Nu]e,f\[Nu]\[Mu],z,x]+\[Rho]intBar[z,x])];
(*Total Energy Density*)
\[Rho]Bar[f\[Nu]e_,f\[Nu]\[Mu]_,z_Real,x_Real]:=\[Rho]Bar[f\[Nu]e,f\[Nu]\[Mu],z,x]=(N[\[Pi]]^2 z^4)/15.+NIntegrate[2./N[\[Pi]]^2 (y^2 Ek[y,x])/(Exp[Ek[y,x]/z]+1)+1./N[\[Pi]]^2 y^3 (f\[Nu]e[y]+2.f\[Nu]\[Mu][y]),{y,ymin,ymax},Method->{Automatic,"SymbolicProcessing"->0}];


(* ::Input::Initialization:: *)
(*Non-dimensional energy*)
Ek[k_Real,x_Real]:=Sqrt[k^2+x^2]


(* ::Input::Initialization:: *)
(*Massive Particles Non-dimensional Energy*)
eE4:=Sqrt[y4^2+x^2+\[Delta]me2[z,x]];
eE3:=Sqrt[y3^2+x^2+\[Delta]me2[z,x]];
(*Nondimensional Momentum after integrating the Dirac Delta*)
E2P1:=y4+y3-y;
E2P4:=eE4+y3-y;
E2P5:=eE4+eE3-y;
y2P1:=E2P1;
y2P4:=Sqrt[E2P4^2-x^2-\[Delta]me2[z,x]]UnitStep[E2P4^2-x^2-\[Delta]me2[z,x]];
y2P5:=E2P5;


(* ::Input::Initialization:: *)
(*Statistical Factor: Pauli Blocking and Espontaneous Emition*)
eF1:=f\[Nu]e[y3] f\[Nu]e[y4] (1.-f\[Nu]e[y])(1.-f\[Nu]e[y2P1])-f\[Nu]e[y] f\[Nu]e[y2P1] (1.-f\[Nu]e[y3])(1.-f\[Nu]e[y4]);
eF2:=f\[Nu]e[y3] f\[Nu]\[Mu][y4] (1.-f\[Nu]e[y])(1.-f\[Nu]\[Mu][y2P1])-f\[Nu]e[y] f\[Nu]\[Mu][y2P1] (1.-f\[Nu]e[y3])(1.-f\[Nu]\[Mu][y4]);
eF3:=f\[Nu]\[Mu][y3] f\[Nu]\[Mu][y4] (1.-f\[Nu]e[y])(1.-f\[Nu]e[y2P1])-f\[Nu]e[y] f\[Nu]e[y2P1] (1.-f\[Nu]\[Mu][y3])(1.-f\[Nu]\[Mu][y4]);
eF4:=f\[Nu]e[y3] fe[eE4,z] (1.-f\[Nu]e[y])(1.-fe[E2P4,z])-f\[Nu]e[y] fe[E2P4,z] (1.-f\[Nu]e[y3])(1.-fe[eE4,z]);
eF5:=fe[eE3,z] fe[eE4,z] (1.-f\[Nu]e[y])(1.-f\[Nu]e[y2P5])-f\[Nu]e[y] f\[Nu]e[y2P5] (1.-fe[eE3,z])(1.-fe[eE4,z]);


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 1: \[Nu]e + \[Nu]e \[Rule] \[Nu]e + \[Nu]e*)
eDk1:=6. D1[y,y2P1,y3,y4]E2P1- (4.D2[y3,y2P1,y,y4]E2P1)/(y y4)-(4.D2[y,y4,y2P1,y3])/y3+(2.D2[y3,y4,y,y2P1])/y+(2.D2[y,y2P1,y3,y4]E2P1)/(y3 y4)+(6.D3[y,y2P1,y3,y4])/(y y3 y4);


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 2: \[Nu]e + \[Nu]\[Mu] \[Rule] \[Nu]e + \[Nu]\[Mu]*)
eDk2:= 4. D1[y,y2P1,y3,y4]E2P1+(2.D2[y3,y4,y,y2P1])/y+(2.D2[y,y2P1,y3,y4]E2P1)/(y3 y4)- (2.D2[y3,y2P1,y,y4]E2P1)/(y y4)- (2.D2[y,y4,y2P1,y3])/y3+(4.D3[y,y2P1,y3,y4])/(y y3 y4);


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 3: \[Nu]e + \[Nu]e \[Rule] \[Nu]\[Mu] + \[Nu]\[Mu]*)
eDk3:= 2. D1[y,y2P1,y3,y4]E2P1-(2.D2[y,y4,y2P1,y3])/y3- (2.D2[y3,y2P1,y,y4]E2P1)/(y y4)+(2.D3[y,y2P1,y3,y4])/(y y3 y4);


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 4: \[Nu]e + e \[Rule] \[Nu]e + e*)
eDk4:=4.(gL^2+gR^2)( 2.D1[y,y2P4,y3,y4] E2P4-D2[y,y4,y2P4,y3]/y3-(D2[y3,y2P4,y,y4] E2P4)/(y eE4)+(D2[y,y2P4,y3,y4] E2P4)/(y3 eE4)+D2[y3,y4,y,y2P4]/y+(2.D3[y,y2P4,y3,y4])/(y y3 eE4))-8.gL gR me^2 (me/x)^-2 (D1[y,y2P4,y3,y4]/eE4 -D2[y4,y2P4,y,y3]/(y y3 eE4));


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 5: \[Nu]e + \[Nu]e \[Rule] e + e*)
eDk5:=4.gL^2 ( D1[y,y2P5,y3,y4]E2P5- D2[y,y4,y2P5,y3]/eE3-  (D2[y3,y2P5,y,y4]E2P5)/(y eE4)+D3[y,y2P5,y3,y4]/(y eE3 eE4))+4.gR^2 (D1[y,y2P5,y3,y4]E2P5-D2[y,y3,y2P5,y4]/eE4-(D2[y4,y2P5,y,y3]E2P5)/(y eE3)+D3[y,y2P5,y3,y4]/(y eE3 eE4))+4.gR gL me^2 (me/x)^-2 ((D1[y,y2P5,y3,y4]E2P5)/(eE3 eE4)+D2[y3,y4,y,y2P5]/(y eE3 eE4));


(* ::Input::Initialization:: *)
(*Collision Integral*)
eIntegral[F\[Nu]e_,F\[Nu]\[Mu]_,Z_Real,X_Real,Y_Real]:=Block[{f\[Nu]e=F\[Nu]e,f\[Nu]\[Mu]=F\[Nu]\[Mu],z=Z,x=X,y=Y},Quiet@NIntegrate[y3 y4((eF1 eDk1+eF2 eDk2+eF3 eDk3)unitstep[y3+y4-y]+eF4 eDk4 unitstep[y3+eE4-y-x]+eF5 eDk5 unitstep[eE3+eE4-y]),
{y3,ymin,ymax},{y4,ymin,ymax},Method->{Automatic,"SymbolicProcessing"->0},AccuracyGoal->AG,MaxPoints->MP]];


(* ::Input::Initialization:: *)
(*Derivative in x of f\[Nu]e*)
\[CapitalDelta]f\[Nu]e[F\[Nu]e_,F\[Nu]\[Mu]_,Z_Real,X_Real,Y_Real]:=1./(X H[F\[Nu]e,F\[Nu]\[Mu],Z,X]) GF^2/(2.N[\[Pi]]^3) 1/Y (me/X)^3 eIntegral[F\[Nu]e,F\[Nu]\[Mu],Z,X,Y]


(* ::Input::Initialization:: *)
(*Statistical Factor: Pauli Blocking and Espontaneous Emition*)
\[Mu]F1:=f\[Nu]\[Mu][y3] f\[Nu]\[Mu][y4] (1.-f\[Nu]\[Mu][y])(1.-f\[Nu]\[Mu][y2P1])-f\[Nu]\[Mu][y] f\[Nu]\[Mu][y2P1] (1.-f\[Nu]\[Mu][y3])(1.-f\[Nu]\[Mu][y4]);
\[Mu]F2:=f\[Nu]\[Mu][y3] f\[Nu]e[y4] (1.-f\[Nu]\[Mu][y])(1.-f\[Nu]e[y2P1])-f\[Nu]\[Mu][y] f\[Nu]e[y2P1] (1.-f\[Nu]\[Mu][y3])(1.-f\[Nu]e[y4]);
\[Mu]F3:=f\[Nu]e[y3]f\[Nu]e[y4] (1.-f\[Nu]\[Mu][y])(1.-f\[Nu]\[Mu][y2P1])-f\[Nu]\[Mu][y] f\[Nu]\[Mu][y2P1] (1.-f\[Nu]e[y3])(1.-f\[Nu]e[y4]);
\[Mu]F4:=f\[Nu]\[Mu][y3] fe[eE4,z] (1.-f\[Nu]\[Mu][y])(1.-fe[E2P4,z])-f\[Nu]\[Mu][y] fe[E2P4,z] (1.-f\[Nu]\[Mu][y3])(1.-fe[eE4,z]);
\[Mu]F5:=fe[eE3,z] fe[eE4,z] (1.-f\[Nu]\[Mu][y])(1.-f\[Nu]\[Mu][y2P5])-f\[Nu]\[Mu][y] f\[Nu]\[Mu][y2P5] (1.-fe[eE3,z])(1.-fe[eE4,z]);


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 1*)
\[Mu]Dk1:= 9. D1[y,y2P1,y3,y4]E2P1-(6.D2[y3,y2P1,y,y4]E2P1)/(y y4)- (6.D2[y,y4,y2P1,y3])/y3+(3.D2[y3,y4,y,y2P1])/y+(3.D2[y,y2P1,y3,y4]E2P1)/(y3 y4)+(9.D3[y,y2P1,y3,y4])/(y y3 y4);


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 2*)
\[Mu]Dk2:= 2. D1[y,y2P1,y3,y4]E2P1+D2[y3,y4,y,y2P1]/y+(D2[y,y2P1,y3,y4]E2P1)/(y3 y4)- (D2[y3,y2P1,y,y4]E2P1)/(y y4)- D2[y,y4,y2P1,y3]/y3+(2.D3[y,y2P1,y3,y4])/(y y3 y4);


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 3*)
\[Mu]Dk3:= D1[y,y2P1,y3,y4]E2P1- D2[y,y4,y2P1,y3]/y3- (D2[y3,y2P1,y,y4]E2P1)/(y y4)+D3[y,y2P1,y3,y4]/(y y3 y4);


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 4*)
\[Mu]Dk4:=4.(g\[Mu]L^2+gR^2) (2.D1[y,y2P4,y3,y4]E2P4-D2[y,y4,y2P4,y3]/y3-(D2[y3,y2P4,y,y4]E2P4)/(y eE4)+(D2[y,y2P4,y3,y4]E2P4)/(y3 eE4)+D2[y3,y4,y,y2P4]/y+(2.D3[y,y2P4,y3,y4])/(y y3 eE4))-8.g\[Mu]L gR me^2 (me/x)^-2 (D1[y,y2P4,y3,y4]/(y3 eE4)-D2[y4,y2P4,y,y3]/(y y3 y3 eE4))E2P4;


(* ::Input::Initialization:: *)
(*Dk Functions for the Term 5*)
\[Mu]Dk5:=4.g\[Mu]L^2 (D1[y,y2P5,y3,y4]E2P5-D2[y,y4,y2P5,y3]/eE3-(D2[y3,y2P5,y,y4]E2P5)/(y eE4)+D3[y,y2P5,y3,y4]/(y eE3 eE4))+4.gR^2 (D1[y,y2P5,y3,y4]E2P5-D2[y,y3,y2P5,y4]/eE4- (D2[y4,y2P5,y,y3]E2P5)/(y eE3)+D3[y,y2P5,y3,y4]/(y eE3 eE4))+4.gR g\[Mu]L me^2 (me/x)^-2 ((D1[y,y2P5,y3,y4]E2P5)/(eE3 eE4)+D2[y3,y4,y,y2P5]/(y eE3 eE4));


(* ::Input::Initialization:: *)
(*Collision Integral*)
\[Mu]Integral[F\[Nu]e_,F\[Nu]\[Mu]_,Z_Real,X_Real,Y_Real]:=
Block[{f\[Nu]e=F\[Nu]e,f\[Nu]\[Mu]=F\[Nu]\[Mu],z=Z,x=X,y=Y},Quiet@NIntegrate[y3 y4((\[Mu]F1 \[Mu]Dk1+\[Mu]F2 \[Mu]Dk2+\[Mu]F3 \[Mu]Dk3)unitstep[y3+y4-y]+\[Mu]F4 \[Mu]Dk4 unitstep[y3+eE4-y-x]+\[Mu]F5 \[Mu]Dk5 unitstep[eE3+eE4-y]),
{y3,ymin,ymax},{y4,ymin,ymax},Method->{Automatic,"SymbolicProcessing"->0},AccuracyGoal->AG,MaxPoints->MP]];


(* ::Input::Initialization:: *)
(*Derivative in x of f\[Nu]\[Mu]*)
\[CapitalDelta]f\[Nu]\[Mu][F\[Nu]e_,F\[Nu]\[Mu]_,Z_Real,X_Real,Y_Real]:=1./(X H[F\[Nu]e,F\[Nu]\[Mu],Z,X]) GF^2/(2.N[\[Pi]]^3) 1/Y (me/X)^3 \[Mu]Integral[F\[Nu]e,F\[Nu]\[Mu],Z,X,Y]


(* ::Input::Initialization:: *)
(*Internal Integrals*)
Der\[CapitalKappa][u_]:=-(1/N[\[Pi]]^2)NIntegrate[u^2 \[Omega] (1+(Sqrt[u^2+\[Omega]^2]+1)Exp[Sqrt[u^2+\[Omega]^2]])/((Exp[Sqrt[u^2+\[Omega]^2]]+1.)^2 (u^2+\[Omega]^2)^(3/2)),{\[Omega],ymin,ymax}];
DerJ[v_]:=-(1/N[\[Pi]]^2)NIntegrate[\[Omega]^2 v Exp[Sqrt[v^2+\[Omega]^2]]/Sqrt[v^2+\[Omega]^2] (Exp[Sqrt[v^2+\[Omega]^2]]-1)/(Exp[Sqrt[v^2+\[Omega]^2]]+1.)^3,{\[Omega],ymin,ymax}];
\[CapitalKappa][\[Kappa]_]:=1/N[\[Pi]]^2 NIntegrate[\[Omega]^2/Sqrt[\[Omega]^2+\[Kappa]^2] 1/(Exp[Sqrt[\[Omega]^2+\[Kappa]^2]]+1.),{\[Omega],ymin,ymax}];
J[\[Mu]_]:=1/N[\[Pi]]^2 NIntegrate[\[Omega]^2 Exp[Sqrt[\[Omega]^2+\[Mu]^2]]/(Exp[Sqrt[\[Omega]^2+\[Mu]^2]]+1.)^2,{\[Omega],ymin,ymax}];
Y[\[Tau]_]:=1/N[\[Pi]]^2 NIntegrate[\[Omega]^4 Exp[Sqrt[\[Omega]^2+\[Tau]^2]]/(Exp[Sqrt[\[Omega]^2+\[Tau]^2]]+1.)^2,{\[Omega],ymin,ymax}];
G1[d_]:=2\[Pi] \[Alpha](1/d (\[CapitalKappa][d]/3.+2\[CapitalKappa][d]^2-J[d]/6.-\[CapitalKappa][d]J[d])+(Der\[CapitalKappa][d]/6.-\[CapitalKappa][d]Der\[CapitalKappa][d]+DerJ[d]/6.+DerJ[d]\[CapitalKappa][d]+Der\[CapitalKappa][d]J[d]));
G2[f_]:=-8\[Pi] \[Alpha](\[CapitalKappa][f]/6.+J[f]/6.-1/2. \[CapitalKappa][f]^2+\[CapitalKappa][f]J[f])+2\[Pi] \[Alpha] f(Der\[CapitalKappa][f]/6.-\[CapitalKappa][f]Der\[CapitalKappa][f]+DerJ[f]/6.+DerJ[f]\[CapitalKappa][f]+J[f]Der\[CapitalKappa][f]);


(* ::Input::Initialization:: *)
(*Continuity Equation*)
CE[df\[Nu]e_,df\[Nu]\[Mu]_,z_Real,x_Real]:=(x/z J[x/z]-1/(2.\[Pi]^2 z^3) NIntegrate[y^3 (df\[Nu]e[y]+2.df\[Nu]\[Mu][y]),{y,ymin,ymax},AccuracyGoal->5]+G1[x/z])/((x/z)^2 J[x/z]+Y[x/z]+(2N[\[Pi]]^2)/15.+G2[x/z]);


(* ::Input::Initialization:: *)
(*Interpolation Functions in y*)
f\[Nu]e=F\[Nu]e=Interpolation[Table[{y1[[i]],f\[Nu]0[y1[[i]]]},{i,n}],InterpolationOrder->interpOrder];
f\[Nu]\[Mu]=F\[Nu]\[Mu]=Interpolation[Table[{y1[[i]],f\[Nu]0[y1[[i]]]},{i,n}],InterpolationOrder->interpOrder];


(* ::Input::Initialization:: *)
(*Lists to Interpolate in y*)
f\[Nu]eList=Table[{0.,0.},n];
f\[Nu]\[Mu]List=Table[{0.,0.},n];
(*List to Interpolate: Derivative \[PartialD]f/\[PartialD]x*)
derf\[Nu]e=Table[{0.,0.},n];
derf\[Nu]\[Mu]=Table[{0.,0.},n];

(*Spectra Distorions*)
distortionsf\[Nu]e={};
distortionsf\[Nu]\[Mu]={};


(* ::Input::Initialization:: *)
(*Global Variables and Functions to Parallelize*)
SetSharedVariable[f\[Nu]eList,f\[Nu]\[Mu]List,derf\[Nu]\[Mu],derf\[Nu]e,iteratorY];


(* ::Input::Initialization:: *)
(*Icoll neglecting*)
probe[list1_,list2_,x_]:=If[Max[list1[[All,2]]]<10.^-8&&Max[list2[[All,2]]]<10.^-8&&x>4.,Clear[\[CapitalDelta]f\[Nu]e,\[CapitalDelta]f\[Nu]\[Mu]];\[CapitalDelta]f\[Nu]e[F\[Nu]e_,F\[Nu]\[Mu]_,Z_Real,X_Real,Y_Real]:=0.;\[CapitalDelta]f\[Nu]\[Mu][F\[Nu]e_,F\[Nu]\[Mu]_,Z_Real,X_Real,Y_Real]:=0.;];
